### ISSUE TITLE
Lista de sugerencias subida documento

### ISSUE THREAD

**Issue by alexmussor** [SanIdeas/LABMMBA#2]
A veces, en la edición de información de un documento, antes de subirlo, al intentar seleccionar un elemento en la lista de sugerencias de nombres no ocurre acción alguna, o en otros casos, la lista desaparece omitiendo el nombre seleccionado.

Por otra parte, luego de unos segundos de que aparezca el formulario para editar el documento antes de subirlo, la lista de sugerencias aparece a pesar de no posicionarse en el input para editar el nombre de este.

**Comment by hrherrer** [comment]
Se arregló el problema con las sugerencias de Crossref. Ahora el cuadro se cierra solo cuando se hace clic fuera del área (entrada de texto + cuadro de sugerencias) o si se seleccionó exitosamente una sugerencia. Además, el cuadro se abre solo cuando el usuario hace clic sobre la entrada de texto.
