### ISSUE TITLE
Noticias sin título

### ISSUE THREAD

**Issue by alexmussor** [SanIdeas/LABMMBA#5]
Si se publican y apruebas noticias sin título, estas aparecen como None tanto en la sección de inicio (header y noticias en la parte inferior), como en la sección Noticias

**Comment by hrherrer** [comment]
Ahora cuando se crea una noticia, antes de que el usuario la edite, se le asigna automáticamente el título "Noticia sin título". Además, cuando se edita una noticia y se deja sin título, se rellena automáticamente con "Noticia sin título".

Ya no deberían aparecer noticias con título None
